# frozen_string_literal: true

source "https://rubygems.org"

gem "blueprinter"
gem "puma"
gem "rackup"
gem "rake"
gem "sequel"
gem "sinatra"
gem "sqlite3"

group :development, :test do
  gem "database_cleaner-sequel"
  gem "debug"
  gem "rack-test"
  gem "rspec"
  gem "rspec-swag"
end
